# Generated by Django 3.2.4 on 2021-06-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=10, max_digits=19)),
                ('marca', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
